// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ_X0LRb_eZKM5xbtXf4tHVyOJe1Zob-0',
    appId: '1:218721550122:web:427a2a14c2af8870d5a853',
    messagingSenderId: '218721550122',
    projectId: 'freelancer-1133e',
    authDomain: 'freelancer-1133e.firebaseapp.com',
    storageBucket: 'freelancer-1133e.appspot.com',
    measurementId: 'G-95YWH0L66S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB54kws0XGwOCgt1K6uCnYsLhACGTguaNs',
    appId: '1:218721550122:android:d0629ab7a1da13d5d5a853',
    messagingSenderId: '218721550122',
    projectId: 'freelancer-1133e',
    storageBucket: 'freelancer-1133e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8BknA39_evoqVIY7JBl_Fl9cr1KDXDAc',
    appId: '1:218721550122:ios:f5aa0b4392e51ed3d5a853',
    messagingSenderId: '218721550122',
    projectId: 'freelancer-1133e',
    storageBucket: 'freelancer-1133e.appspot.com',
    iosBundleId: 'com.example.freelancer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8BknA39_evoqVIY7JBl_Fl9cr1KDXDAc',
    appId: '1:218721550122:ios:f5aa0b4392e51ed3d5a853',
    messagingSenderId: '218721550122',
    projectId: 'freelancer-1133e',
    storageBucket: 'freelancer-1133e.appspot.com',
    iosBundleId: 'com.example.freelancer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ_X0LRb_eZKM5xbtXf4tHVyOJe1Zob-0',
    appId: '1:218721550122:web:162d2bf260b285b9d5a853',
    messagingSenderId: '218721550122',
    projectId: 'freelancer-1133e',
    authDomain: 'freelancer-1133e.firebaseapp.com',
    storageBucket: 'freelancer-1133e.appspot.com',
    measurementId: 'G-B800TL3J3H',
  );
}
